name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: npm
      - run: npm ci
      - name: Run lint, format and type checks
        run: |
          npm run lint:nofix -- --max-warnings=0
          npm run format:check
          npm run type-check
      - name: Check for differences in generated APIs
        run: |
          npm run gen-api
          git diff --exit-code ./src/lib/apis/generated || {
            echo "Generated APIs are outdated or modified. Please run 'npm run gen-api' and commit the changes."
            exit 1
          }
      - name: Check for differences in msw worker
        run: |
          npx msw init
          git diff --exit-code public/mockServiceWorker.js || {
            echo "public/mockServiceWorker.js is outdated. Please run 'npx msw init' and commit the changes."
            exit 1
          }

  build_and_deploy_staging:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    needs: [check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_KEY }}
          known_hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}
      - name: Deploy
        run: rsync -e ssh --rsync-path='sudo rsync' -rltpzhv --delete ./dist ${{ secrets.STAGING_DEPLOY_USER }}@${{ secrets.STAGING_DEPLOY_HOST }}:${{ secrets.STAGING_DEPLOY_RSYNC_DESTINATION }}
